replicaCount: 1
image:
  repository: jasoncalalang/cspb-registrar-api
  tag: "1.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
ingress:
  enabled: true
  annotations: {}
  host: example.com
  tls:
    enabled: true
    hosts:
      - example.com
    secretName: tls-secret
spring:
  datasource:
    url: ""
    username: ""
    password: ""
