apiVersion: v1
kind: Service
metadata:
  name: {{ include "registrar-api.fullname" . }}
  labels:
    app: {{ include "registrar-api.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "registrar-api.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
