openapi: 3.0.1
info:
  title: Registrar API
  version: 1.0.0
paths:
  /api/students:
    get:
      summary: List students
      parameters:
        - in: query
          name: lastName
          schema:
            type: string
          description: Optional last name filter
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
    post:
      summary: Create a student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
  /api/students/{id}:
    get:
      summary: Get student by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '404':
          description: Not found
    put:
      summary: Replace student
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '404':
          description: Not found
    patch:
      summary: Patch student
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Patched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '404':
          description: Not found
    delete:
      summary: Delete student
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No content
        '404':
          description: Not found
  /api/students/{id}/address:
    get:
      summary: Retrieve a student's address
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        '404':
          description: Not found
    put:
      summary: Replace a student's address
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        '404':
          description: Not found
    delete:
      summary: Delete a student's address
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No content
        '404':
          description: Not found
  /requirement-types:
    get:
      summary: List requirement types
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RequirementType'
  /api/students/{id}/requirements:
    get:
      summary: Get requirements for a student
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Requirement'
        '404':
          description: Not found
    patch:
      summary: Batch update requirements
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Requirement'
      responses:
        '204':
          description: No content
        '404':
          description: Not found
  /api/students/{id}/requirements/{typeId}:
    put:
      summary: Set/update a requirement
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: typeId
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Requirement'
      responses:
        '204':
          description: No content
        '404':
          description: Not found
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique student identifier
        lrn:
          type: string
          description: Learner reference number
        lastName:
          type: string
          description: Last name
        firstName:
          type: string
          description: First name
        middleName:
          type: string
          description: Middle name
        extensionName:
          type: string
          description: Name extension
        birthDate:
          type: string
          format: date
          description: Date of birth
        birthPlace:
          type: string
          description: Place of birth
        gender:
          type: string
          description: Gender
        nationality:
          type: string
          description: Nationality
        religion:
          type: string
          description: Religion
        numSiblings:
          type: integer
          format: int32
          description: Number of siblings
        siblingNames:
          type: string
          description: Names of siblings
        imgPath:
          type: string
          description: Image path
        createdAt:
          type: string
          format: date-time
          description: Time record was created
        updatedAt:
          type: string
          format: date-time
          description: Time record was last updated
    Address:
      type: object
      properties:
        houseNo:
          type: string
          description: House number
        streetSubd:
          type: string
          description: Street or subdivision
        bgyCode:
          type: string
          description: Barangay code
    Requirement:
      type: object
      properties:
        requirementTypeId:
          type: integer
          format: int32
          description: Requirement type identifier
        submitted:
          type: boolean
          description: Whether the requirement was submitted
        submittedDate:
          type: string
          format: date
          description: Date of submission
    RequirementType:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Requirement type identifier
        name:
          type: string
          description: Requirement name

