name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build
        run: ./gradlew clean build

      - name: Test
        run: ./gradlew test

      - name: Build Docker image
        run: docker build -t jasoncalalang/cspb-registrar-api:1.0 .

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: jasoncalalang/cspb-registrar-api:1.0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Login to IBM Cloud
        uses: IBM/actions-ibmcloud-cli@v1
        with:
          plugins: container-service

      - name: IBM Cloud Login
        run: ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} -g default -r jp-tok

      - name: Configure cluster
        run: ibmcloud ks cluster config -c d1e1256t0a9klfmaes1g

      - name: Deploy to Kubernetes
        env:
          INGRESS_HOST: ${{ secrets.INGRESS_HOST }}
          TLS_HOST: ${{ secrets.TLS_HOST }}
          TLS_SECRET: ${{ secrets.TLS_SECRET }}
          DATASOURCE_URL: ${{ vars.DATASOURCE_URL }}
          DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
          DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
        run: |
          helm upgrade --install registrar ./kube \
            --set ingress.host=$INGRESS_HOST \
            --set ingress.tls.hosts[0]=$TLS_HOST \
            --set ingress.tls.secretName=$TLS_SECRET \
            --set spring.datasource.url=$DATASOURCE_URL \
            --set spring.datasource.username=$DATASOURCE_USERNAME \
            --set spring.datasource.password=$DATASOURCE_PASSWORD
